### PR TITLE
merging my recent updates from the metadata-updates branch

### PR DESCRIPTION
**Pull request by supervised**

### CODE REVIEW

**Comment by samira-tasnim** [comment]
Dear Pyspedas team,

I am trying to use the following command to access cluster data.

f_vars = pyspedas.cluster.fgm(datatype='cp', trange=['2018-11-6',
'2018-11-7'])

However, it doesn't work. The above command only works for datatype='up',
but doesn't work for 'cp'. Please note that I can download the data using
'downloadonly=True' and then to use the cdf file.

Is it possible to access the 'cp' datatype without downloading as like the
'up'? Any help will be greatly appreciated.


Best regards,
Samira

**Comment by supervised** [comment]
> Dear Pyspedas team, I am trying to use the following command to access cluster data. f_vars = pyspedas.cluster.fgm(datatype='cp', trange=['2018-11-6', '2018-11-7']) However, it doesn't work. The above command only works for datatype='up', but doesn't work for 'cp'. Please note that I can download the data using 'downloadonly=True' and then to use the cdf file. Is it possible to access the 'cp' datatype without downloading as like the 'up'? Any help will be greatly appreciated. Best regards, Samira

Thanks for the bug report! 

The CP files don't follow the ISTP metadata guidelines, so pytplot was ignoring all of the variables. I just sent a patch to pytplot that should fix the problem for these files; pytplot v1.7.27 and later should work.

`pip install pytplot --upgrade`

should get you the bug fix.

**Comment by samira-tasnim** [comment]
Dear PySpedas Team,

Is there a way that the library looks for the data on the local hard drive
first each time I run the code? Right now, it is downloading the data every
time.  It is time-consuming to test the code while we use the same data.

How does 'no_update work'? Any solution/suggestion will be highly
appreciated.

Best regards,
Samira

**Comment by supervised** [comment]
> Dear PySpedas Team, Is there a way that the library looks for the data on the local hard drive first each time I run the code? Right now, it is downloading the data every time. It is time-consuming to test the code while we use the same data. How does 'no_update work'? Any solution/suggestion will be highly appreciated. Best regards, Samira

Hi Samira,

The no_update functionality works by checking if the file already exists locally prior to downloading it, and if it does, it sends the modification time of the file to the remote server when requesting the file. If the file is current (i.e., the modification time of the file on the remote server matches the modification time of the local file), the server responds with an HTTP 304 (Not Modified) response, and we load the local file (without re-downloading the file). 

Can you provide an example call that re-downloads the data? It definitely shouldn't be doing that.

**Pull request merged**
