### PR TITLE
bug fix for load.py in psp

### PR DESCRIPTION
**Pull request by huangzesen**
a minor bug for lower case...
added basic auth to utilities.download.download_file

### CODE REVIEW

**Comment by STBadman** [comment]
Hi! I have just been running into one of the issues addressed in this PR, that `pyspedas.utilities.download_file` only tries to authorize using `HTTPDigestAuth` and not `HTTPBasicAuth` - thank you @huangzesen for writing this up!

@supervised, if there are no issues with these changes, could you merge them as soon as possible?

**Comment by supervised** [comment]
Sorry for the delay! Merging the fix now

**Comment by STBadman** [comment]
thank you!

**Comment by supervised** [comment]
Update: the PSP branch seems broken, so I moved the bug fix to my branch and committed it from there. It should be available in PyPI now (v1.4.18 or later)

**Comment by STBadman** [comment]
Perfect, I was able to update and can confirm that authorization is now working. thanks for doing that so quickly!

**Pull request merged**
