### PR TITLE
Cloud Awareness for download.py

### PR DESCRIPTION
**Pull request by edmondb**
Changes include Cloud Awareness for the majority of PySPEDAS that calls pyspedas/utilities/download.py using the fsspec filesystem protocol (includes AWS S3 and GCS support) for URIs. The proposed changes do not break current API usage and includes the following functionality:

- Retrieve from http/https servers and place onto local URI-path data storage.
- Read/Stream from URI storage whether given as remote or local.
- Update local URI-path storage from separate remote URI-path storage.
- Allow a user to download from a remote URI (NOT RECOMMENDED) by using the `force_download` option.
- Attempt to read/stream from local storage (posix or URI-based) if the remote download/stream fails.

__Note:__ In order to make a "clean" PR, package dependencies (`fsspec`, `s3fs`, and `aioboto3`) were included in later commits for inclusion into requirements.txt and setup.py. Also, cdflib version requirement including cloud awareness was included.

Future development for custom download methods beyond those using `download.py` will be included in the pull request that will merge this branch with the main branch.

This code was tested using AWS' CLI on an EC2 resource provided by the HelioCloud project. Details for AWS CLI setup and temporary credential management not included, but available.

Updates [416](https://github.com/spedas/pyspedas/issues/416)

### CODE REVIEW

**Comment by jameswilburlewis** [comment]
Thanks very much for all this work....I'm eager to give it a try and see how it works out!

**Comment by edmondb** [comment]
Hey @jameswilburlewis , just seeing if you've had a chance to look at this, need help with it, or perhaps should we change the PR assignment?

Also, we will push more changes in a separate PR for those custom download scripts (like MMS) that will close that opened issue too. So, I hope you're not waiting for that here.

**Comment by jameswilburlewis** [comment]
@edmondb We're in the middle of some major refactoring of the pyspedas source code.  I wanted to hold off on merging this PR, until I'm sure there won't be any conflicts with the stuff we're changing in the master branch.   So far it looks like everything should still work together....I expect I'll be able to do the merge sometime this week.

**Comment by edmondb** [comment]
Sounds good @jameswilburlewis !

**Pull request merged**
